# https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[graph]
targets = []
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  "https://github.com/cjwcommuny/deref_ext",
  "https://github.com/cjwcommuny/async-iter-ext",
  "https://github.com/cjwcommuny/ycsb-rs.git",
]

[sources.allow-org]
# github = [""]
# gitlab = [""]
# bitbucket = [""]
